streams:
  HDMI1:
    url: "rtmp://10.0.0.62/bcs/channel0_ext.bcs?channel=0&stream=0&user=admin&password=curling1"
    image_path: "/home/pi/rpisurv/surveillance/images/connecting.png"
  HDMI2:
    url: "rtmp://10.0.0.62/bcs/channel1_ext.bcs?channel=1&stream=0&user=admin&password=curling2"
    image_path: "/home/pi/rpisurv/surveillance/images/connecting.png"
